.equ STACK_SIZE, 0x1000
.equ BASE_STACK, 0x20000
.equ ABRT_STACK, BASE_STACK+STACK_SIZE
.equ FIQ_STACK , ABRT_STACK+STACK_SIZE
.equ IRQ_STACK , FIQ_STACK+STACK_SIZE
.equ SVC_STACK , IRQ_STACK+STACK_SIZE
.equ SYS_STACK , SVC_STACK+STACK_SIZE
.equ UND_STACK , SYS_STACK+STACK_SIZE
.equ USR_STACK , UND_STACK+STACK_SIZE
.equ ABRT_MD     , 0x17
.equ FIQ_MD      , 0x11
.equ IRQ_MD      , 0x12
.equ SVC_MD      , 0x13
.equ SYS_MD      , 0x1f
.equ UND_MD      , 0x1b
.equ USR_MD      , 0x10

.equ IRQ_MDMASK  , 0xd2
.equ FIRQ_MDMASK , 0xd1

